// Generate lib/api-types.ts from the Rust-derived JSON schemas in
// ../examples/schemas/api (produced by `cargo run --bin schema-gen`). The
// Rust models are the source of truth; never hand-edit the output.
import { compile } from "json-schema-to-typescript";
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const dir = new URL("../../examples/schemas/api/", import.meta.url).pathname;
const files = readdirSync(dir).filter((f) => f.endsWith(".schema.json")).sort();
let out = "// GENERATED by `bun run types` from examples/schemas/api/*.schema.json — do not edit.\n// Source of truth: the Rust models (schema-gen). Re-run after changing them.\n\n";
const seen = new Set();
for (const f of files) {
  const schema = JSON.parse(readFileSync(join(dir, f), "utf8"));
  const name = f.replace(".schema.json", "");
  const ts = await compile(schema, name, { bannerComment: "", additionalProperties: false, declareExternallyReferenced: true });
  // Each file re-declares shared $defs; keep the first declaration only.
  for (const block of ts.split(/\n(?=export )/)) {
    const m = block.match(/^export (?:interface|type) (\w+)/);
    if (!m || !seen.has(m[1])) {
      if (m) seen.add(m[1]);
      out += block.trim() + "\n\n";
    }
  }
}
writeFileSync(new URL("../lib/api-types.ts", import.meta.url), out);
console.log(`wrote lib/api-types.ts (${seen.size} types from ${files.length} schemas)`);
