// GENERATED by `bun run types` from examples/schemas/api/*.schema.json — do not edit.
// Source of truth: the Rust models (schema-gen). Re-run after changing them.

export interface Candidate {
  category?: string | null;
  /**
   * Inputs folded into the plain content slot (columns or image without
   * their own slot) — shown, but not as authored.
   */
  collapses: string[];
  /**
   * The slide's current layout.
   */
  current: boolean;
  /**
   * Body slots this layout places that the slide has nothing for.
   */
  empty: string[];
  /**
   * Slide inputs this layout shows nowhere.
   */
  hides: string[];
  layout: string;
  /**
   * Whether the layout declares PPTX zones (native editable export).
   */
  pptx_zones: boolean;
  /**
   * Higher fits better; 100 means every input has a home and nothing is empty.
   */
  score: number;
  tags: string[];
}

export interface Hit {
  /**
   * Effective layout (`layout:` field, else `default`).
   */
  layout: string;
  matched: FieldHit[];
  name: string;
  relative_path: string;
  /**
   * Higher is better. Only meaningful for ordering within one query.
   */
  score: number;
  tags: string[];
  title?: string | null;
  topic?: string | null;
}
/**
 * Where a query matched inside one slide, with a short excerpt.
 */

export interface FieldHit {
  /**
   * `name`, `title`, `tags`, `topic`, `description`, or `body`.
   */
  field: string;
  /**
   * The matching text — the tag, the title, or a window of body text
   * around the first hit.
   */
  snippet: string;
}

/**
 * Everything known about one layout's use.
 */

export interface LayoutUsage {
  layout: string;
  slides: string[];
}

export type MediaKind = "image" | "video" | "other";

export interface MediaIndex {
  files: MediaFile[];
}
/**
 * One file in a media folder.
 */

export interface MediaFile {
  bytes: number;
  file_name: string;
  /**
   * The slide folder this belongs to; empty for the library-level folder.
   */
  folder: string;
  kind: MediaKind;
  /**
   * Path relative to the slide directory: `genai/media/x.png`, or
   * `../media/logo.svg` for the library-level folder (which sits beside
   * `slides/`). A slide in `genai/` references the latter as
   * `../../media/logo.svg`.
   */
  path: string;
  /**
   * Slides (relative paths) whose body references this file.
   */
  used_by: string[];
}

/**
 * Metadata from a slide's YAML frontmatter
 */

export interface SlideMetadata {
  /**
   * Horizontal alignment of slide content: "left", "center", "right".
   * Overrides the layout's default. Applied as `data-align` on the
   * slide section so CSS can pin alignment without changing markup.
   */
  align?: string | null;
  /**
   * Author of the slide
   */
  author?: string | null;
  /**
   * Creation date
   */
  created?: string | null;
  /**
   * Brief description of the slide content
   */
  description?: string | null;
  /**
   * Per-slide override for the deck footer line (the `{{footer}}` slot).
   * Falls back to the flavor's `footer` when omitted.
   */
  footer?: string | null;
  /**
   * Preferred layout
   */
  layout?: string | null;
  /**
   * Last modified date
   */
  modified?: string | null;
  /**
   * Research area this slide belongs to
   */
  research_area?: string | null;
  /**
   * Source attribution for web-clipping slides — display text shown as
   * a "Source: …" line via the `{{source}}` slot. Pair with `source_url`
   * to make it a link.
   */
  source?: string | null;
  /**
   * Optional link target for `source`. When set, the source line becomes
   * a hyperlink (still self-contained; only resolved if the viewer clicks).
   */
  source_url?: string | null;
  /**
   * Subheadline — the smaller line under the headline in a framed
   * layout's chrome zone (exposed as the `{{subheadline}}` slot).
   */
  subtitle?: string | null;
  /**
   * Tags for categorization
   */
  tags?: string[];
  /**
   * Slide title
   */
  title?: string | null;
  /**
   * Topic or category
   */
  topic?: string | null;
  /**
   * Per-language overrides for the framed-chrome fields, keyed by language
   * code (e.g. `de`, `fr`). The top-level fields are the default language;
   * a `translations.<lang>` block overrides the chrome for that language,
   * and any omitted field falls back to the top-level value. This is the
   * frontmatter analog of the body's `::lang:xx::` markers — so a deck
   * built with `--lang de` translates the headline/subtitle/source, not
   * just the body. A slide with no `translations` block is unchanged.
   */
  translations?: {
    [k: string]: ChromeTranslation;
  };
  /**
   * Per-slide type scale: multiplies every `--sldr-type-scale`-aware font
   * size on this slide (body, lists, cards, timeline …). `0.85` squeezes a
   * dense table or list onto the slide without dropping to raw HTML;
   * `1.2` enlarges a sparse one. Clamped to 0.5–2 at render time.
   */
  type_scale?: number | null;
  /**
   * Vertical alignment of slide content: "top", "center", "bottom".
   * Overrides the layout's default. Applied as `data-valign` on the
   * slide section.
   */
  valign?: string | null;
}
/**
 * Per-language overrides for the translatable framed-chrome fields. Any
 * field left unset falls back to the slide's top-level (default-language)
 * value — so a translator only fills the fields that actually differ.
 */

export interface ChromeTranslation {
  footer?: string | null;
  source?: string | null;
  source_url?: string | null;
  subtitle?: string | null;
  title?: string | null;
}

/**
 * Everything known about one slide's use.
 */

export interface SlideUsage {
  last_touched?: GitTouch | null;
  playlists: PlaylistRef[];
  slide: string;
}
/**
 * The last git commit that touched a path.
 */

export interface GitTouch {
  commit: string;
  /**
   * ISO-8601 committer date.
   */
  date: string;
}
/**
 * One playlist that references a slide.
 */

export interface PlaylistRef {
  flavor?: string | null;
  name: string;
  /**
   * Total slides in that playlist.
   */
  of: number;
  /**
   * 1-based position of the slide in the playlist.
   */
  position: number;
  title?: string | null;
}

/**
 * Slide → playlists, for a whole library. Build once, look up many.
 */

export interface UsageIndex {
  playlists: number;
  /**
   * Keyed by the slide's library-relative path (`genai/intro.md`).
   */
  slides: {
    [k: string]: PlaylistRef[];
  };
  unresolved: Unresolved[];
}
/**
 * One playlist that references a slide.
 */

export interface Unresolved {
  entry: string;
  playlist: string;
  reason: string;
}

/**
 * What fills a zone.
 */

export type Binding =
  | {
      field: string;
      kind: "frontmatter";
    }
  | {
      kind: "markdown";
      /**
       * @minItems 2
       * @maxItems 2
       */
      range?: [unknown, unknown] | null;
      slot: string;
    }
  | {
      kind: "image";
      slot: string;
      src?: string | null;
    }
  | {
      field: string;
      kind: "flavor";
    }
  | {
      kind: "none";
    };
/**
 * Where an edit to a zone's *content* is written. Geometry is never here —
 * a zone's box always belongs to the layout (see [`ZoneDocument::geometry`]).
 */

export type Writes =
  | {
      path: string;
      target: "slide";
    }
  | {
      name: string;
      target: "flavor";
    };

export interface ZoneDocument {
  flavor?: string | null;
  geometry: Geometry;
  /**
   * Language the body and chrome were resolved for.
   */
  language: string;
  layout: string;
  /**
   * The slide's library-relative path.
   */
  slide: string;
  unbound: Unbound[];
  zones: ZoneEntry[];
}
/**
 * Who owns the boxes. Always the layout: there is no per-slide geometry.
 */

export interface Geometry {
  /**
   * `true` when the layout is an embedded built-in (editing its zones
   * writes a library override rather than the built-in).
   */
  builtin: boolean;
  layout: string;
  /**
   * How many slides use this layout, when the caller knows (where-used).
   */
  used_by?: number | null;
}
/**
 * Slide input that no zone of the current layout shows. Mirrors the PPTX
 * exporter's accounting so nothing is silently invisible: a `::left::` body
 * on a plain layout, a `subtitle` on a layout without a subheadline zone.
 */

export interface Unbound {
  binding: Binding;
  name: string;
}
/**
 * One zone of the document: the layout's declaration plus what the join knows.
 */

export interface ZoneEntry {
  binding: Binding;
  /**
   * Percent of the slide box: `[x, y, w, h]`.
   *
   * @minItems 4
   * @maxItems 4
   */
  box: [number, number, number, number];
  /**
   * The bound content as it stands (plain text for frontmatter/flavor
   * fields, raw markdown for body segments, the src for images).
   */
  content?: string | null;
  idx?: number | null;
  name: string;
  ph?: string | null;
  /**
   * Representation policy token (`placeholder-text`, `picture`, `shape`, `bake`).
   */
  rep: string;
  /**
   * Where a content edit lands. `None` for decoration zones.
   */
  writes?: Writes | null;
}

