//! Round-trip import (trx-4s9s.5): a sldr-generated `.pptx` → slide markdown.
//!
//! This is the deterministic *inverse* of [`crate::build_deck`], not heuristic
//! recognition of arbitrary PowerPoint (ADR-0008, the epic's scope guard). It
//! works because the export embeds its own mapping in the package:
//!
//! - each slide references its `slideLayout`, whose `<p:cSld name="…">` is the
//!   sldr **layout name** → the `layout:` frontmatter;
//! - every placeholder/picture carries the **zone name** in its `cNvPr name`
//!   (`Headline`, `Content`, `Left`, `Image`, …) → which frontmatter field or
//!   body segment it came from;
//! - `<Application>sldr</Application>` marks the deck as ours.
//!
//! Import refuses a deck that isn't sldr-generated. What maps is reconstructed
//! faithfully (chrome, bulleted/plain body, embedded pictures); genuinely
//! off-script edits a user made in PowerPoint are reported by the caller, never
//! silently invented. A few corners are lossy by nature (a heading and a bold
//! paragraph both round-trip to bold text) — that's the honest wall.

use std::collections::HashMap;
use std::io::Read;

use anyhow::{bail, Context, Result};
use quick_xml::events::Event;
use quick_xml::Reader;

/// One slide reconstructed from a deck.
#[derive(Debug, Default, Clone)]
pub struct ImportedSlide {
    pub layout: String,
    pub title: Option<String>,
    pub subtitle: Option<String>,
    pub footer: Option<String>,
    pub source: Option<String>,
    pub source_url: Option<String>,
    /// Reconstructed markdown body (with `::left::`/`::content::`/`::image::`
    /// markers when the layout shape calls for them).
    pub body: String,
    /// Embedded pictures, in slide order: `(suggested_filename, bytes)`.
    pub images: Vec<ImportedImage>,
}

#[derive(Debug, Clone)]
pub struct ImportedImage {
    pub file_name: String,
    pub bytes: Vec<u8>,
}

/// Parse a sldr-generated `.pptx` (raw bytes) into its slides. Fails loud if
/// the package isn't a sldr deck.
pub fn import(pptx: &[u8]) -> Result<Vec<ImportedSlide>> {
    let mut zip = zip::ZipArchive::new(std::io::Cursor::new(pptx))
        .context("not a valid .pptx (zip) package")?;

    let app = read_string(&mut zip, "docProps/app.xml").unwrap_or_default();
    if !app.contains("<Application>sldr</Application>") {
        bail!(
            "this .pptx was not generated by sldr — import is a deterministic \
             inverse of sldr export, not a general PowerPoint reader"
        );
    }

    // Slide order from the presentation's sldIdLst → rels → slide parts.
    let pres = read_string(&mut zip, "ppt/presentation.xml")
        .context("missing ppt/presentation.xml")?;
    let pres_rels = read_string(&mut zip, "ppt/_rels/presentation.xml.rels").unwrap_or_default();
    let rel_targets = parse_rels(&pres_rels);
    let slide_paths: Vec<String> = sld_id_rids(&pres)
        .into_iter()
        .filter_map(|rid| rel_targets.get(&rid).cloned())
        .map(|t| normalize_ppt_path(&t))
        .collect();

    let mut slides = Vec::new();
    for slide_path in slide_paths {
        let slide_xml = read_string(&mut zip, &slide_path)
            .with_context(|| format!("missing slide part {slide_path}"))?;
        let rels_path = sibling_rels_path(&slide_path);
        let rels_xml = read_string(&mut zip, &rels_path).unwrap_or_default();
        let rels = parse_rels(&rels_xml);

        // Layout name from the referenced slideLayout's cSld@name.
        let layout = rels
            .iter()
            .find(|(_, t)| t.contains("slideLayout"))
            .map(|(_, t)| normalize_ppt_path(t))
            .and_then(|p| read_string(&mut zip, &p).ok())
            .and_then(|x| csld_name(&x))
            .unwrap_or_else(|| "default".to_string());

        let shapes = parse_slide(&slide_xml)?;
        let mut slide = ImportedSlide {
            layout,
            ..Default::default()
        };

        // Bucket parsed shapes by zone name.
        let mut zones: HashMap<String, Vec<Para>> = HashMap::new();
        for shape in shapes {
            let zone = shape.name.to_lowercase();
            if let Some(embed) = shape.embed {
                // Picture: resolve the embedded media via the slide rels.
                if let Some(target) = rels.get(&embed) {
                    let media_path = normalize_ppt_path(target);
                    if let Ok(bytes) = read_bytes(&mut zip, &media_path) {
                        let ext = media_path.rsplit('.').next().unwrap_or("png");
                        slide.images.push(ImportedImage {
                            file_name: format!("{}.{ext}", slug_or(&slide.title, slides.len())),
                            bytes,
                        });
                    }
                }
            } else {
                zones.insert(zone, shape.paragraphs);
            }
        }

        // Chrome zones → frontmatter (plain text). An empty placeholder means
        // the field was absent on export — drop it, don't emit `footer: `.
        let chrome = |k: &str| {
            zones
                .get(k)
                .map(|p| plain_text(p))
                .filter(|s| !s.is_empty())
        };
        slide.title = chrome("headline");
        slide.subtitle = chrome("subheadline");
        slide.footer = chrome("footer");
        if let Some(src) = chrome("source") {
            let (s, u) = parse_source(&src);
            slide.source = (!s.is_empty()).then_some(s);
            slide.source_url = u;
        }

        slide.body = assemble_body(&zones, !slide.images.is_empty());
        slides.push(slide);
    }

    Ok(slides)
}

/// Markdown body from the body zones, choosing markers by which zones exist.
fn assemble_body(zones: &HashMap<String, Vec<Para>>, has_image: bool) -> String {
    let md = |k: &str| zones.get(k).map(|p| paras_to_markdown(p)).unwrap_or_default();
    let heading = md("heading");
    let left = zones.contains_key("left");
    let content = zones.contains_key("content");

    let mut out = String::new();
    if !heading.is_empty() {
        out.push_str(&heading);
        out.push_str("\n\n");
    }
    if left {
        out.push_str("::left::\n");
        out.push_str(&md("left"));
        out.push_str("\n\n::right::\n");
        out.push_str(&md("right"));
    } else if content && has_image {
        out.push_str("::content::\n");
        out.push_str(&md("content"));
        out.push_str("\n\n::image::\n![](IMAGE)");
    } else {
        out.push_str(&md("content"));
    }
    out.trim().to_string()
}

// ---- OOXML slide parsing ----------------------------------------------

#[derive(Debug, Default)]
struct Para {
    bullet: bool,
    level: usize,
    runs: Vec<Run>,
}

#[derive(Debug, Default)]
struct Run {
    text: String,
    bold: bool,
    italic: bool,
    mono: bool,
}

#[derive(Debug, Default)]
struct Shape {
    name: String,
    paragraphs: Vec<Para>,
    /// `r:embed` id when this shape is a `<p:pic>`.
    embed: Option<String>,
}

/// Walk a slide's spTree, returning each shape's zone name + content.
fn parse_slide(xml: &str) -> Result<Vec<Shape>> {
    let mut reader = Reader::from_str(xml);
    reader.config_mut().trim_text(false);

    let mut shapes = Vec::new();
    let mut shape: Option<Shape> = None;
    let mut para: Option<Para> = None;
    let mut run: Option<Run> = None;
    let mut in_text = false;

    loop {
        match reader.read_event()? {
            Event::Eof => break,
            Event::Start(e) | Event::Empty(e) => {
                let name = e.name();
                match name.as_ref() {
                    b"p:sp" | b"p:pic" => shape = Some(Shape::default()),
                    b"p:cNvPr" => {
                        if let Some(s) = shape.as_mut() {
                            if let Some(v) = attr(&e, b"name") {
                                s.name = v;
                            }
                        }
                    }
                    b"a:blip" => {
                        if let Some(s) = shape.as_mut() {
                            // r:embed is namespaced; match by local suffix.
                            s.embed = attr(&e, b"r:embed").or_else(|| attr(&e, b"embed"));
                        }
                    }
                    b"a:p" => para = Some(Para::default()),
                    b"a:pPr" => {
                        if let Some(p) = para.as_mut() {
                            if let Some(lvl) = attr(&e, b"lvl").and_then(|v| v.parse().ok()) {
                                p.level = lvl;
                            }
                        }
                    }
                    b"a:buChar" => {
                        if let Some(p) = para.as_mut() {
                            p.bullet = true;
                        }
                    }
                    b"a:r" => run = Some(Run::default()),
                    b"a:rPr" => {
                        if let Some(r) = run.as_mut() {
                            r.bold = attr(&e, b"b").as_deref() == Some("1");
                            r.italic = attr(&e, b"i").as_deref() == Some("1");
                        }
                    }
                    b"a:latin" => {
                        if let Some(r) = run.as_mut() {
                            if let Some(tf) = attr(&e, b"typeface") {
                                if tf.eq_ignore_ascii_case("Consolas") {
                                    r.mono = true;
                                }
                            }
                        }
                    }
                    b"a:t" => in_text = true,
                    _ => {}
                }
            }
            Event::Text(t) => {
                if in_text {
                    if let Some(r) = run.as_mut() {
                        r.text.push_str(&t.unescape().unwrap_or_default());
                    }
                }
            }
            Event::End(e) => match e.name().as_ref() {
                b"a:t" => in_text = false,
                b"a:r" => {
                    if let (Some(p), Some(r)) = (para.as_mut(), run.take()) {
                        if !r.text.is_empty() {
                            p.runs.push(r);
                        }
                    }
                }
                b"a:p" => {
                    if let (Some(s), Some(p)) = (shape.as_mut(), para.take()) {
                        s.paragraphs.push(p);
                    }
                }
                b"p:sp" | b"p:pic" => {
                    if let Some(s) = shape.take() {
                        if !s.name.is_empty() {
                            shapes.push(s);
                        }
                    }
                }
                _ => {}
            },
            _ => {}
        }
    }
    Ok(shapes)
}

/// Bold/italic/mono → markdown emphasis; concatenated across runs.
fn inline(runs: &[Run]) -> String {
    let mut out = String::new();
    for r in runs {
        let mut t = r.text.clone();
        if r.mono {
            t = format!("`{t}`");
        } else {
            if r.italic {
                t = format!("*{t}*");
            }
            if r.bold {
                t = format!("**{t}**");
            }
        }
        out.push_str(&t);
    }
    out
}

/// All runs of all paragraphs joined as one plain line (chrome).
fn plain_text(paras: &[Para]) -> String {
    paras
        .iter()
        .map(|p| p.runs.iter().map(|r| r.text.as_str()).collect::<String>())
        .collect::<Vec<_>>()
        .join(" ")
        .trim()
        .to_string()
}

/// Body paragraphs → markdown: bullets become `- …` (indented by level),
/// plain paragraphs are separated by blank lines.
fn paras_to_markdown(paras: &[Para]) -> String {
    let mut out = String::new();
    let mut prev_bullet = false;
    for (i, p) in paras.iter().enumerate() {
        let line = inline(&p.runs);
        if line.is_empty() {
            continue;
        }
        if i > 0 {
            out.push_str(if p.bullet && prev_bullet { "\n" } else { "\n\n" });
        }
        if p.bullet {
            out.push_str(&"  ".repeat(p.level));
            out.push_str("- ");
        }
        out.push_str(&line);
        prev_bullet = p.bullet;
    }
    out
}

/// Reverse the exported `Label text (url)` source string.
fn parse_source(s: &str) -> (String, Option<String>) {
    // Drop the localized "Source:"/"Quelle:" label up to the first colon.
    let body = match s.find(':') {
        Some(i) => s[i + 1..].trim(),
        None => s.trim(),
    };
    if body.ends_with(')') {
        if let Some(open) = body.rfind('(') {
            let url = body[open + 1..body.len() - 1].trim().to_string();
            let text = body[..open].trim().to_string();
            if url.starts_with("http") {
                return (text, Some(url));
            }
        }
    }
    (body.to_string(), None)
}

// ---- tiny XML/zip helpers ---------------------------------------------

fn read_string(zip: &mut zip::ZipArchive<std::io::Cursor<&[u8]>>, path: &str) -> Result<String> {
    let mut f = zip.by_name(path)?;
    let mut s = String::new();
    f.read_to_string(&mut s)?;
    Ok(s)
}

fn read_bytes(zip: &mut zip::ZipArchive<std::io::Cursor<&[u8]>>, path: &str) -> Result<Vec<u8>> {
    let mut f = zip.by_name(path)?;
    let mut v = Vec::new();
    f.read_to_end(&mut v)?;
    Ok(v)
}

/// One attribute value by qualified key, unescaped.
fn attr(e: &quick_xml::events::BytesStart, key: &[u8]) -> Option<String> {
    e.attributes().flatten().find_map(|a| {
        if a.key.as_ref() == key {
            a.unescape_value().ok().map(|v| v.into_owned())
        } else {
            None
        }
    })
}

/// `Id → Target` from a `.rels` part.
fn parse_rels(xml: &str) -> HashMap<String, String> {
    let mut reader = Reader::from_str(xml);
    let mut map = HashMap::new();
    while let Ok(ev) = reader.read_event() {
        match ev {
            Event::Eof => break,
            Event::Empty(e) | Event::Start(e) if e.name().as_ref() == b"Relationship" => {
                if let (Some(id), Some(target)) = (attr(&e, b"Id"), attr(&e, b"Target")) {
                    map.insert(id, target);
                }
            }
            _ => {}
        }
    }
    map
}

/// Ordered `r:id`s from `<p:sldIdLst>`.
fn sld_id_rids(pres_xml: &str) -> Vec<String> {
    let mut reader = Reader::from_str(pres_xml);
    let mut ids = Vec::new();
    while let Ok(ev) = reader.read_event() {
        match ev {
            Event::Eof => break,
            Event::Empty(e) | Event::Start(e) if e.name().as_ref() == b"p:sldId" => {
                if let Some(rid) = attr(&e, b"r:id").or_else(|| attr(&e, b"id")) {
                    // r:id, not the numeric id; prefer the r:id attribute.
                    if rid.starts_with("rId") {
                        ids.push(rid);
                    } else if let Some(r) = attr(&e, b"r:id") {
                        ids.push(r);
                    }
                }
            }
            _ => {}
        }
    }
    ids
}

/// `<p:cSld name="…">` of a slideLayout.
fn csld_name(xml: &str) -> Option<String> {
    let mut reader = Reader::from_str(xml);
    while let Ok(ev) = reader.read_event() {
        match ev {
            Event::Eof => break,
            Event::Empty(e) | Event::Start(e) if e.name().as_ref() == b"p:cSld" => {
                return attr(&e, b"name");
            }
            _ => {}
        }
    }
    None
}

/// Resolve a rels Target (often `../slideLayouts/x.xml` or `slides/x.xml`)
/// into a package-absolute path under `ppt/`.
fn normalize_ppt_path(target: &str) -> String {
    let t = target.trim_start_matches('/');
    if let Some(rest) = t.strip_prefix("../") {
        format!("ppt/{rest}")
    } else if t.starts_with("ppt/") {
        t.to_string()
    } else {
        format!("ppt/{t}")
    }
}

/// `ppt/slides/slide1.xml` → `ppt/slides/_rels/slide1.xml.rels`.
fn sibling_rels_path(part: &str) -> String {
    match part.rfind('/') {
        Some(i) => format!("{}/_rels/{}.rels", &part[..i], &part[i + 1..]),
        None => format!("_rels/{part}.rels"),
    }
}

/// A filename slug from a title, or `slide-N`.
fn slug_or(title: &Option<String>, idx: usize) -> String {
    title
        .as_deref()
        .map(|t| {
            t.to_lowercase()
                .chars()
                .map(|c| if c.is_alphanumeric() { c } else { '-' })
                .collect::<String>()
                .trim_matches('-')
                .to_string()
        })
        .filter(|s| !s.is_empty())
        .unwrap_or_else(|| format!("slide-{}", idx + 1))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::deck::{build_deck, SlideInput, ZoneContent};
    use crate::Theme;
    use sldr_renderer::LayoutRegistry;

    fn theme() -> Theme {
        Theme::from_parts(
            "demo", Some("#0F172A"), Some("#FFF"), Some("#3B82F6"), Some("#F59E0B"),
            Some("#E2E8F0"), Some("#94A3B8"), Some("Inter"), Some("Inter"),
        )
    }

    #[test]
    fn test_round_trip_framed() {
        let reg = LayoutRegistry::builtin();
        let framed = reg.get("framed").unwrap();
        let slides = vec![SlideInput {
            layout: framed,
            fields: vec![
                ("headline".into(), ZoneContent::Text("My Title".into())),
                (
                    "content".into(),
                    ZoneContent::Markdown("- first **bold**\n- second".into()),
                ),
                ("footer".into(), ZoneContent::Text("ACME".into())),
            ],
        }];
        let bytes = build_deck(&theme(), "Deck", &slides).unwrap();

        let imported = import(&bytes).unwrap();
        assert_eq!(imported.len(), 1);
        let s = &imported[0];
        assert_eq!(s.layout, "framed");
        assert_eq!(s.title.as_deref(), Some("My Title"));
        assert_eq!(s.footer.as_deref(), Some("ACME"));
        assert!(s.body.contains("- first **bold**"));
        assert!(s.body.contains("- second"));
    }

    #[test]
    fn test_round_trip_two_cols_markers() {
        let reg = LayoutRegistry::builtin();
        let two = reg.get("two-cols").unwrap();
        let slides = vec![SlideInput {
            layout: two,
            fields: vec![
                ("left".into(), ZoneContent::Markdown("- L1".into())),
                ("right".into(), ZoneContent::Markdown("- R1".into())),
            ],
        }];
        let bytes = build_deck(&theme(), "Deck", &slides).unwrap();
        let imported = import(&bytes).unwrap();
        let s = &imported[0];
        assert_eq!(s.layout, "two-cols");
        assert!(s.body.contains("::left::"));
        assert!(s.body.contains("::right::"));
        assert!(s.body.contains("- L1"));
        assert!(s.body.contains("- R1"));
    }

    #[test]
    fn test_import_rejects_non_sldr_deck() {
        // A zip without the sldr app marker.
        let parts = vec![("docProps/app.xml".to_string(), "<x/>".to_string())];
        let bytes = crate::zip_parts(&parts).unwrap();
        let err = import(&bytes).unwrap_err().to_string();
        assert!(err.contains("not generated by sldr"));
    }

    #[test]
    fn test_round_trip_picture() {
        let reg = LayoutRegistry::builtin();
        let il = reg.get("image-left").unwrap();
        let slides = vec![SlideInput {
            layout: il,
            fields: vec![
                ("content".into(), ZoneContent::Markdown("- point".into())),
                (
                    "image".into(),
                    ZoneContent::Picture {
                        bytes: b"\x89PNG fake".to_vec(),
                        ext: "png".into(),
                        fit: None,
                    },
                ),
            ],
        }];
        let bytes = build_deck(&theme(), "Deck", &slides).unwrap();
        let imported = import(&bytes).unwrap();
        let s = &imported[0];
        assert_eq!(s.images.len(), 1);
        assert!(s.body.contains("::content::"));
        assert!(s.body.contains("::image::"));
    }
}
