//! Deterministic bounded inverse of native export, never a foreign-deck reader.
//! Unknown objects and formatting have explicit dispositions, not silent skips.
use std::collections::{BTreeMap, BTreeSet};
use anyhow::{bail, Context, Result};
use roxmltree::Node;
use crate::{Conversion, Disposition, Report};
use crate::package::{Package, A, P, R};

#[derive(Debug, Default, Clone)]
pub struct ImportedSlide {
    pub layout: String,
    pub title: Option<String>,
    pub subtitle: Option<String>,
    pub footer: Option<String>,
    pub source: Option<String>,
    pub source_url: Option<String>,
    pub body: String,
    pub images: Vec<ImportedImage>,
    pub identity: Option<String>,
    pub source_id: Option<String>,
    pub step: usize,
    pub notes: Option<String>,
    /// Language the slide was exported in, when the package records it.
    pub language: Option<String>,
    /// Every recognised zone with its value and whether it was edited since
    /// export — what `import --apply` writes back, zone by zone.
    pub zones: Vec<ImportedZone>,
}
#[derive(Debug, Clone)]
pub struct ImportedImage { pub file_name: String, pub bytes: Vec<u8> }

/// One zone as it came back from PowerPoint.
#[derive(Debug, Clone)]
pub struct ImportedZone {
    /// Zone name (`headline`, `content`, `image`, …).
    pub zone: String,
    /// Text zones: plain text (chrome) or markdown (body). Pictures: empty.
    pub value: String,
    /// Picture zones: the embedded image.
    pub image: Option<ImportedImage>,
    /// `Some(true)` edited since export, `Some(false)` untouched, `None`
    /// unknown (no identity record, or a picture whose bytes must be
    /// compared against the source file by the caller).
    pub changed: Option<bool>,
    /// `slide` or `flavor` — who owned the content at export.
    pub owner: String,
}

/// Strict by default. Use `import_with_report` and explicitly review its report
/// to authorize lossy conversion. Neither operation writes source files.
pub fn import(bytes: &[u8]) -> Result<Vec<ImportedSlide>> {
    let result = import_with_report(bytes)?;
    result.report.enforce(false)?;
    Ok(result.value)
}

pub fn import_with_report(bytes: &[u8]) -> Result<Conversion<Vec<ImportedSlide>>> {
    let package = Package::read(bytes)?;
    let manifest = crate::identity::load(&package)?;
    let app = package.text("docProps/app.xml").unwrap_or_default();
    if manifest.is_none() && !app.contains("<Application>sldr</Application>") {
        bail!("this .pptx was not generated by sldr — external import is not authorized");
    }
    let mut report = package.validate()?;
    if manifest.is_none() {
        report.record(None, "docProps/app.xml", "Application", "legacy_identity", Disposition::Unsupported,
            "Legacy display-name mapping has no stable ownership proof; --allow-lossy imports into new files only");
    }
    let paths = package.slides()?;
    let mut slides = Vec::new();
    let mut seen = BTreeSet::new();
    for (i, path) in paths.iter().enumerate() {
        let doc = package.xml(path)?;
        let record = manifest.as_ref().and_then(|m| crate::identity::record_for(m, doc.root_element(), path, &mut seen, &mut report));
        slides.push(read_slide(&package, path, i, record, &mut report)?);
    }
    if let Some(manifest) = &manifest {
        for record in &manifest.slides {
            if !seen.contains(&record.id) {
                report.record(Some(&record.id), "customXml/sldr.xml", &record.id, "missing_slide", Disposition::Conflicting,
                    "A recorded source slide is missing; reconcile deletion explicitly");
            }
        }
    }
    Ok(Conversion { value: slides, report })
}

fn read_slide(package: &Package, path: &str, index: usize, record: Option<&crate::identity::SlideRecord>, report: &mut Report) -> Result<ImportedSlide> {
    let doc = package.xml(path)?;
    let rels = package.rels(path)?;
    let layout_rel = rels.iter().find(|r| r.kind == format!("{R}/slideLayout") && !r.external)
        .context("slide has no layout relationship")?;
    let layout_doc = package.xml(&layout_rel.target)?;
    let layout = layout_doc.descendants().find(|n| n.has_tag_name((P, "cSld")))
        .and_then(|n| n.attribute("name")).context("layout has no sldr name")?.to_owned();
    let mut slide = ImportedSlide {
        layout: record.map(|r| r.layout.clone()).unwrap_or(layout),
        identity: record.map(|r| r.id.clone()), source_id: record.map(|r| r.source_id.clone()),
        step: record.map(|r| r.step).unwrap_or(0), language: record.and_then(|r| r.language.clone()),
        ..Default::default()
    };
    let mut owners: BTreeMap<String, String> = BTreeMap::new();
    let mut zones = BTreeMap::new();
    let mut elements_seen = BTreeSet::new();
    let tree = doc.descendants().find(|n| n.has_tag_name((P, "spTree"))).context("slide has no shape tree")?;
    for shape in tree.children().filter(Node::is_element) {
        if shape.has_tag_name((P, "nvGrpSpPr")) || shape.has_tag_name((P, "grpSpPr")) { continue; }
        let props = shape.descendants().find(|n| n.has_tag_name((P, "cNvPr")));
        let id = props.and_then(|n| n.attribute("id")).unwrap_or("unknown");
        let identity = props.and_then(crate::identity::node_id);
        let mapped = record.and_then(|r| identity.and_then(|id| r.elements.get(id)));
        if let Some(element) = mapped {
            if !elements_seen.insert(identity.unwrap_or_default().to_owned()) {
                report.record(Some(path), path, id, "duplicate_element_identity", Disposition::Conflicting,
                    "Resolve duplicated element ownership");
            }
            if crate::identity::structure_hash(shape) != element.structure_hash {
                report.record(Some(path), path, id, "changed_structure", Disposition::Unsupported,
                    "Element geometry/structure differs from its baseline; only supported content edits map back");
            }
        }
        let zone = if let Some(mapped) = mapped { mapped.zone.clone() }
            else if record.is_some() { String::new() }
            else { props.and_then(|n| n.attribute("name")).unwrap_or("").to_lowercase() };
        let known = matches!(zone.as_str(), "headline" | "subheadline" | "footer" | "source" | "heading" | "content" | "left" | "right" | "image");
        let pic = shape.has_tag_name((P, "pic"));
        let placeholder = shape.descendants().any(|n| n.has_tag_name((P, "ph")));
        if !known || !(pic || (shape.has_tag_name((P, "sp")) && placeholder)) {
            report.record(Some(path), path, id, &format!("unmapped_{}", shape.tag_name().name()), Disposition::Unsupported,
                "Added or unmapped object cannot be assigned to a source zone; keep original or explicitly allow omission");
            continue;
        }
        if zones.contains_key(&zone) {
            report.record(Some(path), path, id, "duplicate_zone", Disposition::Conflicting,
                "Resolve duplicate zone ownership before import");
            continue;
        }
        audit_shape(shape, path, id, pic, report);
        let value = if pic {
            let rid = shape.descendants().find(|n| n.has_tag_name((A, "blip")))
                .and_then(|n| n.attribute((R, "embed"))).context("picture has no embedded relationship")?;
            let media = rels.iter().find(|r| r.id == rid && r.kind == format!("{R}/image") && !r.external)
                .context("picture relationship is not an internal image")?;
            let ext = media.target.rsplit('.').next().unwrap_or("bin");
            let file_name = format!("slide-{}-image-{}.{}", index + 1, slide.images.len() + 1, ext);
            slide.images.push(ImportedImage {
                file_name,
                bytes: package.parts.get(&media.target).context("missing picture bytes")?.clone(),
            });
            "![](IMAGE)".to_string()
        } else { paragraphs(shape, &rels) };
        let changed = mapped.map(|element| {
            if pic { None } else { Some(crate::identity::text_hash(shape) != element.content_hash) }
        }).flatten();
        let owner = mapped.map(|e| e.owner.clone()).unwrap_or_else(|| "slide".into());
        owners.insert(zone.clone(), owner.clone());
        slide.zones.push(ImportedZone {
            zone: zone.clone(),
            value: if pic { String::new() } else { value.clone() },
            image: if pic { slide.images.last().cloned() } else { None },
            changed,
            owner,
        });
        zones.insert(zone, value);
        report.record(Some(path), path, id, "zone_content", Disposition::Converted,
            "Text/image content converted; see separate geometry/style findings");
    }
    if let Some(record) = record {
        for id in record.elements.keys().filter(|id| !elements_seen.contains(*id)) {
            report.record(Some(&record.id), path, id, "missing_element", Disposition::Conflicting,
                "A recorded element was removed or its identity was stripped; reconcile explicitly");
        }
    }
    let chrome = |name: &str| zones.get(name).filter(|v| !v.is_empty()).cloned();
    slide.title = chrome("headline");
    slide.subtitle = chrome("subheadline");
    // A flavor-owned footer is style chrome, not slide content (ADR-0008):
    // never copy it into the slide's frontmatter.
    slide.footer = chrome("footer").filter(|_| owners.get("footer").is_none_or(|o| o == "slide"));
    if let Some(source) = chrome("source") {
        let (label, url) = parse_source(&source);
        slide.source = Some(label);
        slide.source_url = url;
    }
    slide.body = assemble_body(&zones);
    match crate::notes::extract(package, &rels) {
        Ok(Some(notes)) => { slide.notes = Some(notes);
            report.record(Some(path), path, "notes", "speaker_notes", Disposition::Converted,
                "Speaker notes preserved as Markdown; see any formatting notes above"); }
        Ok(None) => {}
        Err(error) => report.record(Some(path), path, "notes", "speaker_notes", Disposition::Unsupported,
            &format!("Notes could not be read: {error:#}")),
    }
    // Account for slide-level extensions, transitions, timing, background, etc.
    for child in doc.root_element().children().filter(Node::is_element) {
        if !child.has_tag_name((P, "cSld")) && !child.has_tag_name((P, "clrMapOvr")) && !crate::identity::is_identity_node(child) {
            report.record(Some(path), path, child.tag_name().name(), "slide_property", Disposition::Unsupported,
                "Slide-level property is not represented in Markdown");
        }
    }
    Ok(slide)
}

fn audit_shape(shape: Node<'_, '_>, path: &str, id: &str, picture: bool, report: &mut Report) {
    for node in shape.descendants().filter(Node::is_element) {
        if crate::identity::is_identity_node(node) { continue; }
        let name = node.tag_name().name();
        let known = match node.tag_name().namespace() {
            Some(P) => matches!(name, "sp" | "pic" | "nvSpPr" | "nvPicPr" | "cNvPr" | "cNvSpPr" | "cNvPicPr" | "nvPr" | "ph" | "spPr" | "txBody" | "blipFill"),
            Some(A) => matches!(name, "bodyPr" | "lstStyle" | "p" | "pPr" | "r" | "rPr" | "t" | "latin" | "buNone" | "buFont" | "buChar" | "buAutoNum" | "br" | "hlinkClick" | "spLocks" | "picLocks" | "endParaRPr") ||
                (picture && matches!(name, "blip" | "stretch" | "fillRect" | "xfrm" | "off" | "ext" | "prstGeom" | "avLst")),
            _ => false,
        };
        if !known {
            report.record(Some(path), path, &format!("{id}/{name}"), "unsupported_xml", Disposition::Unsupported,
                "This geometry, formatting or extension is not represented in imported Markdown");
        }
        let allowed: &[&str] = match name {
            "cNvPr" => &["id", "name"], "ph" => &["type", "idx"],
            "rPr" | "endParaRPr" => &["lang", "b", "i", "dirty", "sz", "strike"],
            "buAutoNum" => &["type", "startAt"], "hlinkClick" => &["id"],
            "pPr" => &["lvl", "marL", "indent"], "latin" | "buFont" => &["typeface"],
            "buChar" => &["char"], "spLocks" => &["noGrp"], "picLocks" => &["noChangeAspect"],
            "blip" => &["embed"], "off" => &["x", "y"], "ext" => &["cx", "cy"],
            "prstGeom" => &["prst"], _ => &[],
        };
        for attr in node.attributes() {
            // A size is understood only as a heading level; any other size
            // is a formatting edit markdown cannot carry.
            let heading_size = attr.name() == "sz"
                && attr.value().parse::<u32>().is_ok_and(|v| crate::mdooxml::HEADING_SIZES.contains(&v));
            if !allowed.contains(&attr.name()) || (attr.name() == "sz" && !heading_size) {
                report.record(Some(path), path, &format!("{id}/{name}@{}", attr.name()), "unsupported_attribute", Disposition::Unsupported,
                    "Formatting/property omitted; retain original or explicitly authorize loss");
            }
        }
    }
}

/// A shape's paragraphs back to markdown — the inverse of `mdooxml`:
/// bullets, auto-numbering (with its start), headings by size, block quotes
/// by indent, bold/italic/strike/code runs, hard breaks and hyperlinks.
fn paragraphs(shape: Node<'_, '_>, rels: &[crate::package::Relationship]) -> String {
    let mut out = String::new();
    let mut prev_list = false;
    let mut prev_ordered = false;
    // Next number per nesting level for consecutive auto-numbered paragraphs.
    let mut counters: Vec<u64> = Vec::new();
    for para in shape.descendants().filter(|n| n.has_tag_name((A, "p"))) {
        let ppr = para.children().find(|n| n.has_tag_name((A, "pPr")));
        let bullet = para.descendants().any(|n| n.has_tag_name((A, "buChar")));
        let autonum = para.descendants().find(|n| n.has_tag_name((A, "buAutoNum")));
        let level: usize = ppr.and_then(|n| n.attribute("lvl")).and_then(|v| v.parse().ok()).unwrap_or(0).min(8);
        let mar_l: i64 = ppr.and_then(|n| n.attribute("marL")).and_then(|v| v.parse().ok()).unwrap_or(0);
        let runs: Vec<Node> = para.children().filter(|n| n.has_tag_name((A, "r")) || n.has_tag_name((A, "br"))).collect();
        let sizes: Vec<u32> = runs.iter().filter(|n| n.has_tag_name((A, "r")))
            .filter_map(|r| r.children().find(|n| n.has_tag_name((A, "rPr")))?.attribute("sz")?.parse().ok())
            .collect();
        let heading = (!sizes.is_empty() && sizes.len() == runs.iter().filter(|n| n.has_tag_name((A, "r"))).count())
            .then(|| crate::mdooxml::HEADING_SIZES.iter().position(|&h| sizes.iter().all(|&s| s == h)))
            .flatten();
        let quote = !bullet && autonum.is_none() && heading.is_none() && mar_l >= crate::mdooxml::QUOTE_MARL;

        let mut text = String::new();
        for run in &runs {
            if run.has_tag_name((A, "br")) { text.push_str("  \n"); continue; }
            let props = run.children().find(|n| n.has_tag_name((A, "rPr")));
            let flag = |name: &str| props.and_then(|p| p.attribute(name)).is_some_and(|b| b == "1" || b == "true");
            let bold = flag("b") && heading.is_none();
            let italic = flag("i") && !quote;
            let strike = props.and_then(|p| p.attribute("strike")).is_some_and(|v| v != "noStrike");
            let mono = run.descendants().any(|n| n.has_tag_name((A, "latin")) && n.attribute("typeface") == Some("Consolas"));
            let link = props.and_then(|p| p.children().find(|n| n.has_tag_name((A, "hlinkClick"))))
                .and_then(|h| h.attribute((R, "id")))
                .and_then(|id| rels.iter().find(|r| r.id == id && r.external))
                .map(|r| r.target.clone());
            let mut value = run.children().filter(|n| n.has_tag_name((A, "t")))
                .filter_map(|n| n.text()).collect::<String>();
            if value.is_empty() { continue; }
            if mono { value = format!("`{value}`"); }
            else {
                if italic { value = format!("*{value}*"); }
                if bold { value = format!("**{value}**"); }
                if strike { value = format!("~~{value}~~"); }
            }
            if let Some(url) = link { value = format!("[{value}]({url})"); }
            text.push_str(&value);
        }
        if text.is_empty() { continue; }
        let is_list = bullet || autonum.is_some();
        // Consecutive items of the same kind of list stay tight; a switch
        // between numbered and bulleted starts a new list (blank line).
        let same_list = is_list && prev_list && (autonum.is_some() == prev_ordered || level > 0);
        if !out.is_empty() { out.push_str(if same_list { "\n" } else { "\n\n" }); }
        if let Some(num) = autonum {
            let start: u64 = num.attribute("startAt").and_then(|v| v.parse().ok()).unwrap_or(1);
            counters.truncate(level + 1);
            while counters.len() <= level { counters.push(0); }
            if !prev_list || counters[level] == 0 { counters[level] = start; }
            out.push_str(&"   ".repeat(level));
            out.push_str(&format!("{}. ", counters[level]));
            counters[level] += 1;
        } else if bullet {
            counters.truncate(level);
            out.push_str(&"  ".repeat(level));
            out.push_str("- ");
        } else {
            counters.clear();
            if let Some(h) = heading { out.push_str(&"#".repeat(h + 1)); out.push(' '); }
            if quote { out.push_str("> "); }
        }
        out.push_str(&text);
        prev_list = is_list;
        if level == 0 { prev_ordered = autonum.is_some(); }
    }
    out
}
fn assemble_body(zones: &BTreeMap<String, String>) -> String {
    let get = |k: &str| zones.get(k).map(String::as_str).unwrap_or("");
    let body = if zones.contains_key("left") {
        format!("::left::\n{}\n\n::right::\n{}", get("left"), get("right"))
    } else if zones.contains_key("image") {
        format!("::content::\n{}\n\n::image::\n{}", get("content"), get("image"))
    } else { get("content").to_owned() };
    if get("heading").is_empty() { body.trim().into() }
    else { format!("{}\n\n{body}", get("heading")).trim().into() }
}
fn parse_source(source: &str) -> (String, Option<String>) {
    let body = source.strip_prefix("Source: ").or_else(|| source.strip_prefix("Quelle: ")).unwrap_or(source);
    if let Some((text, url)) = body.strip_suffix(')').and_then(|b| b.rsplit_once(" (")) {
        if url.starts_with("https://") || url.starts_with("http://") { return (text.into(), Some(url.into())); }
    }
    (body.into(), None)
}
