#[cfg(test)]
mod tests {
    use crate::{import, build_deck, SlideInput, ZoneContent, Theme};
    use sldr_renderer::LayoutRegistry;

    fn theme() -> Theme {
        Theme::from_parts(
            "demo", Some("#0F172A"), Some("#FFF"), Some("#3B82F6"), Some("#F59E0B"),
            Some("#E2E8F0"), Some("#94A3B8"), Some("Inter"), Some("Inter"),
        )
    }

    #[test]
    fn test_round_trip_framed() {
        let reg = LayoutRegistry::builtin();
        let framed = reg.get("framed").unwrap();
        let slides = vec![SlideInput { details: Default::default(),
            layout: framed,
            fields: vec![
                ("headline".into(), ZoneContent::Text("My Title".into())),
                (
                    "content".into(),
                    ZoneContent::Markdown("- first **bold**\n- second".into()),
                ),
                ("footer".into(), ZoneContent::Text("ACME".into())),
            ],
        }];
        let bytes = build_deck(&theme(), "Deck", &slides).unwrap();

        let imported = import(&bytes).unwrap();
        assert_eq!(imported.len(), 1);
        let s = &imported[0];
        assert_eq!(s.layout, "framed");
        assert_eq!(s.title.as_deref(), Some("My Title"));
        assert_eq!(s.footer.as_deref(), Some("ACME"));
        assert!(s.body.contains("- first **bold**"));
        assert!(s.body.contains("- second"));
    }

    #[test]
    fn test_round_trip_two_cols_markers() {
        let reg = LayoutRegistry::builtin();
        let two = reg.get("two-cols").unwrap();
        let slides = vec![SlideInput { details: Default::default(),
            layout: two,
            fields: vec![
                ("left".into(), ZoneContent::Markdown("- L1".into())),
                ("right".into(), ZoneContent::Markdown("- R1".into())),
            ],
        }];
        let bytes = build_deck(&theme(), "Deck", &slides).unwrap();
        let imported = import(&bytes).unwrap();
        let s = &imported[0];
        assert_eq!(s.layout, "two-cols");
        assert!(s.body.contains("::left::"));
        assert!(s.body.contains("::right::"));
        assert!(s.body.contains("- L1"));
        assert!(s.body.contains("- R1"));
    }

    #[test]
    fn test_import_rejects_non_sldr_deck() {
        // A zip without the sldr app marker.
        let parts = vec![("docProps/app.xml".to_string(), "<x/>".to_string())];
        let bytes = crate::zip_parts(&parts).unwrap();
        let err = import(&bytes).unwrap_err().to_string();
        assert!(err.contains("not generated by sldr"));
    }

    #[test]
    fn test_round_trip_picture() {
        let reg = LayoutRegistry::builtin();
        let il = reg.get("image-left").unwrap();
        let slides = vec![SlideInput { details: Default::default(),
            layout: il,
            fields: vec![
                ("content".into(), ZoneContent::Markdown("- point".into())),
                (
                    "image".into(),
                    ZoneContent::Picture {
                        bytes: b"\x89PNG fake".to_vec(),
                        ext: "png".into(),
                        fit: None,
                    },
                ),
            ],
        }];
        let bytes = build_deck(&theme(), "Deck", &slides).unwrap();
        let imported = import(&bytes).unwrap();
        let s = &imported[0];
        assert_eq!(s.images.len(), 1);
        assert!(s.body.contains("::content::"));
        assert!(s.body.contains("::image::"));
    }
}
